default:
  image: python:3.8

  before_script:
    - cd backend_django
    - pip install -r test-requirements.txt

lint:
  script:
    - flake8 .

test:
  script:
    - pip install -r requirements.txt
    - pytest -v --cov=model_garden --cov-report=term-missing --no-cov-on-fail tests
