# Generated by Django 3.0.5 on 2020-05-01 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model_garden', '0004_mediaasset'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bucketitem',
            unique_together={('path', 'bucket')},
        ),
    ]
