# Generated by Django 3.0.6 on 2020-05-05 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_garden', '0006_auto_20200503_0316'),
    ]

    operations = [
        migrations.AddField(
            model_name='bucket',
            name='url',
            field=models.URLField(default='https://d3o54g14k1n39o.cloudfront.net/'),
            preserve_default=False,
        ),
    ]
