# Generated by Django 3.0.6 on 2020-05-06 17:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('model_garden', '0008_mediaasset_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaasset',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
