# Generated by Django 3.0.5 on 2020-05-01 18:19

from django.db import migrations, models


class Migration(migrations.Migration):
  dependencies = [
    ('model_garden', '0002_bucketitem'),
  ]

  operations = [
    migrations.AlterField(
      model_name='bucketitem',
      name='path',
      field=models.CharField(max_length=512),
    ),
  ]
