# Generated by Django 3.0.5 on 2020-05-01 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
  dependencies = [
    ('model_garden', '0003_auto_20200501_1819'),
  ]

  operations = [
    migrations.CreateModel(
      name='MediaAsset',
      fields=[
        ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        ('filename', models.CharField(max_length=512)),
        ('bucket_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model_garden.BucketItem')),
      ],
    ),
  ]
