# Generated by Django 3.0.6 on 2020-05-06 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_garden', '0007_bucket_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaasset',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ASSIGNED', 'Assigned')], default='PENDING', max_length=32),
        ),
    ]
