# Generated by Django 3.0.6 on 2020-05-14 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model_garden', '0011_auto_20200511_2227'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mediaasset',
            unique_together={('filename', 'dataset')},
        ),
    ]
