# Generated by Django 3.0.6 on 2020-05-19 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('model_garden', '0012_auto_20200514_0444'),
    ]

    operations = [
        migrations.CreateModel(
            name='Labeler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('labeler_id', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='mediaasset',
            name='status',
        ),
        migrations.CreateModel(
            name='LabelingTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=256)),
                ('status', models.CharField(choices=[('annotation', 'Annotation'), ('validation', 'Validation'), ('completed', 'Completed')], default='annotation', max_length=16)),
                ('labeler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labeling_tasks', to='model_garden.Labeler')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='labeling_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_assets', to='model_garden.LabelingTask'),
        ),
    ]
