# Generated by Django 3.0.6 on 2020-05-19 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_garden', '0013_auto_20200519_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='labelingtask',
            name='url',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
