# Generated by Django 3.0.6 on 2020-05-20 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_garden', '0015_labelingtask_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labelingtask',
            name='task_id',
            field=models.IntegerField(),
        ),
    ]
