# Generated by Django 3.0.6 on 2020-05-22 19:04

from django.db import migrations, models


class Migration(migrations.Migration):
  dependencies = [
    ('model_garden', '0016_auto_20200520_2137'),
  ]

  operations = [
    migrations.AlterField(
      model_name='labelingtask',
      name='status',
      field=models.CharField(
        choices=[('annotation', 'Annotation'), ('validation', 'Validation'), ('completed', 'Completed'),
                 ('saved', 'Saved'), ('archived', 'Archived')], default='annotation', max_length=16),
    ),
  ]
