# Generated by Django 3.0.6 on 2020-05-29 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_garden', '0018_auto_20200528_0431'),
    ]

    operations = [
        migrations.AddField(
            model_name='labelingtask',
            name='error',
            field=models.TextField(blank=True, null=True),
        ),
    ]
