# Generated by Django 3.0.6 on 2020-06-02 21:54

from django.db import migrations, models


class Migration(migrations.Migration):
  dependencies = [
    ('model_garden', '0019_labelingtask_error'),
  ]

  operations = [
    migrations.AlterField(
      model_name='labelingtask',
      name='status',
      field=models.CharField(
        choices=[('annotation', 'Annotation'), ('validation', 'Validation'), ('completed', 'Completed'),
                 ('saved', 'Saved'), ('archived', 'Archived'), ('failed', 'Failed')], default='annotation',
        max_length=16),
    ),
  ]
