# Generated by Django 3.0.6 on 2020-06-04 16:30

from django.db import migrations, models


def change_dataset_path(apps, schema_editor):
    Dataset = apps.get_model('model_garden', 'Dataset')
    for dataset in Dataset.objects.all().iterator():
        dataset.path = f"/{dataset.path}"
        dataset.save(update_fields=('path',))


class Migration(migrations.Migration):

    dependencies = [
        ('model_garden', '0020_auto_20200602_2154'),
    ]

    operations = [
        migrations.RunPython(change_dataset_path),
    ]
