# Generated by Django 3.0.6 on 2020-09-14 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_garden', '0025_auto_20200914_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaasset',
            name='labeling_asset_filepath',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
